language: java
sudo: required
dist: trusty
group: edge

addons:
  apt:
    packages:
      - oracle-java9-installer
jdk:
  - oraclejdk9

branches:
  only:
    - master

before_install:
  - chmod +x gradlew
  - ./gradlew wrapper

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)