dist: xenial
language: java

jdk: openjdk11

branches:
  only:
    - master

install:
  - chmod +x gradlew
  - ./gradlew wrapper

script: ./gradlew build

cache:
  directories:
  - .autoconf
  - $HOME/.gradle
