language: java
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew
  - ./gradlew wrapper

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)