language: java
sudo: required
dist: trusty
group: edge

addons:
  apt:
    packages:
      - oracle-java9-installer
jdk:
  - oraclejdk9

branches:
  only:
    - master

before_install:
  - chmod +x gradlew
  - ./gradlew wrapper